database:
  driver: h2 # possible drivers are h2, mysql, postgres, mariadb, sqlite
  # see the respective driver for their url
  # e.g. mariadb would be: jdbc:mariadb://localhost:3306/minecraft <-- the database name
  url: 'jdbc:h2:file:~/sstats.db'
  username: minecraft
  password: minecraft